############################################################
# +------------------------------------------------------+ #
# |                       Config                         | #
# +------------------------------------------------------+ #
############################################################

# Webhook URL from your Discord server.
webhook-url: ''

# Bot user.
bot-name: 'George'
bot-picture: 'https://i.pinimg.com/originals/bf/23/ca/bf23ca87c2a867e2b3b991e76d982abd.jpg' #URL

# Color of the Discord embed.
ban-color: '#ff2b2b' # Red
tempban-color: '#ff992b' # Orange
unban-color: '#2afa4d' # Green
banip-color: '#5b09ad' # Purple
unbanip-color: '#0ce6fa' # Light Blue

# What messages should the plugin send?
bans: true
tempbans: true
unbans: true
banips: true
unbanips: true

# Debugging.
debug: false
